// Fallback translations for all remaining languages in LocaleSelector
// These use English as a base with locale-specific translations

// Slovak
export const sk = {
  nav: { book: "Rezervovať", flights: "Lety", myBooking: "Moje rezervácie" },
  home: { hero: "Vaša cesta začína tu", popularDestinations: "Obľúbené destinácie" },
  search: { from: "Z", to: "Do", date: "Dátum", passengers: "Cestujúci", searchFlights: "Hľadať lety", searching: "Hľadám...", adult: "Dospelý", adults: "Dospelí", cabinClass: { economy: "Economy", premium_economy: "Premium Economy", business: "Business", first: "Prvá trieda" } },
  flights: { title: "Dostupné lety", noResults: "Žiadne lety nenájdené", filters: "Filtre", cabinClass: "Trieda kabíny", allClasses: "Všetky triedy", nonStop: "Priamy let", select: "Vybrať", status: { scheduled: "Naplánované", boarding: "Nastupovanie", departed: "Odletel", arrived: "Pristál", cancelled: "Zrušené" } },
  booking: { cabin: { title: "Vybrať triedu", selectFrom: "Vybrať z", soldOut: "Vypredané" }, seat: { title: "Vybrať sedadlo", selected: "Vybrané sedadlo", available: "Dostupné", occupied: "Obsadené", yourSeat: "Vaše sedadlo" }, passenger: { title: "Informácie o cestujúcom", passengerN: "Cestujúci", title_field: "Titul", firstName: "Meno", lastName: "Priezvisko", dateOfBirth: "Dátum narodenia", nationality: "Národnosť", passportNumber: "Číslo pasu" }, contact: { title: "Kontaktné informácie", subtitle: "Potvrdenie rezervácie bude zaslané na tento kontakt.", firstName: "Meno", lastName: "Priezvisko", email: "E-mailová adresa", phone: "Telefónne číslo" }, summary: { title: "Prehľad rezervácie", flight: "Let", cabin: "Trieda", seat: "Sedadlo", passenger: "Cestujúci", contact: "Kontakt", total: "Spolu", confirmAndPay: "Potvrdiť a zaplatiť" }, payment: { title: "Platba", cardNumber: "Číslo karty", expiry: "Platnosť do", cvv: "CVV", name: "Meno držiteľa karty", payNow: "Zaplatiť teraz", processing: "Spracovávam..." }, confirmation: { title: "Rezervácia potvrdená!", subtitle: "Váš let je pripravený. Zabaľte kufre!", reference: "Číslo rezervácie", downloadTicket: "⬇ Stiahnuť e-letenku", backHome: "Späť na hlavnú stránku" } },
  common: { back: "← Späť", next: "Ďalej →", loading: "Načítavam...", error: "Vyskytla sa chyba", close: "Zavrieť" },
  locale: { language: "Jazyk", currency: "Mena", currentLanguage: "Aktuálny jazyk", allLanguages: "Všetky jazyky", popularCurrencies: "Obľúbené meny", allCurrencies: "Všetky meny" },
};

// Bulgarian
export const bg = {
  nav: { book: "Резервирай", flights: "Полети", myBooking: "Моята резервация" },
  home: { hero: "Пътуването ви започва тук", popularDestinations: "Популярни дестинации" },
  search: { from: "От", to: "До", date: "Дата", passengers: "Пътници", searchFlights: "Търси полети", searching: "Търсене...", adult: "Възрастен", adults: "Възрастни", cabinClass: { economy: "Икономична", premium_economy: "Премиум икономична", business: "Бизнес", first: "Първа класа" } },
  flights: { title: "Налични полети", noResults: "Няма намерени полети", filters: "Филтри", cabinClass: "Класа", allClasses: "Всички класи", nonStop: "Директен", select: "Избери", status: { scheduled: "Планиран", boarding: "Качване", departed: "Отлетял", arrived: "Пристигнал", cancelled: "Отменен" } },
  booking: { cabin: { title: "Изберете класа", selectFrom: "Изберете от", soldOut: "Разпродадено" }, seat: { title: "Изберете място", selected: "Избрано място", available: "Свободно", occupied: "Заето", yourSeat: "Вашето място" }, passenger: { title: "Информация за пътника", passengerN: "Пътник", title_field: "Обръщение", firstName: "Собствено име", lastName: "Фамилия", dateOfBirth: "Дата на раждане", nationality: "Гражданство", passportNumber: "Номер на паспорт" }, contact: { title: "Информация за контакт", subtitle: "Потвърждението ще бъде изпратено на този контакт.", firstName: "Собствено ime", lastName: "Фамилия", email: "Имейл адрес", phone: "Телефонен номер" }, summary: { title: "Обобщение на резервацията", flight: "Полет", cabin: "Класа", seat: "Място", passenger: "Пътник", contact: "Контакт", total: "Общо", confirmAndPay: "Потвърди и плати" }, payment: { title: "Плащане", cardNumber: "Номер на карта", expiry: "Валидност", cvv: "CVV", name: "Ime на притежателя", payNow: "Плати сега", processing: "Обработване..." }, confirmation: { title: "Резервацията е потвърдена!", subtitle: "Вашият полет е готов. Наредете куфарите!", reference: "Референтен номер", downloadTicket: "⬇ Изтегли e-билет", backHome: "Начало" } },
  common: { back: "← Назад", next: "Напред →", loading: "Зареждане...", error: "Възникна грешка", close: "Затвори" },
  locale: { language: "Език", currency: "Валута", currentLanguage: "Текущ език", allLanguages: "Всички езици", popularCurrencies: "Популярни валути", allCurrencies: "Всички валути" },
};

// Croatian
export const hr = {
  nav: { book: "Rezerviraj", flights: "Letovi", myBooking: "Moja rezervacija" },
  home: { hero: "Vaše putovanje počinje ovdje", popularDestinations: "Popularne destinacije" },
  search: { from: "Iz", to: "U", date: "Datum", passengers: "Putnici", searchFlights: "Traži letove", searching: "Traženje...", adult: "Odrasli", adults: "Odrasli", cabinClass: { economy: "Ekonomska", premium_economy: "Premium ekonomska", business: "Poslovna", first: "Prva klasa" } },
  flights: { title: "Dostupni letovi", noResults: "Nisu pronađeni letovi", filters: "Filtri", cabinClass: "Klasa kabine", allClasses: "Sve klase", nonStop: "Izravni let", select: "Odaberi", status: { scheduled: "Zakazano", boarding: "Ukrcavanje", departed: "Odletio", arrived: "Stigao", cancelled: "Otkazano" } },
  booking: { cabin: { title: "Odaberi klasu", selectFrom: "Odaberi iz", soldOut: "Rasprodano" }, seat: { title: "Odaberi sjedalo", selected: "Odabrano sjedalo", available: "Dostupno", occupied: "Zauzeto", yourSeat: "Vaše sjedalo" }, passenger: { title: "Podaci putnika", passengerN: "Putnik", title_field: "Titula", firstName: "Ime", lastName: "Prezime", dateOfBirth: "Datum rođenja", nationality: "Nacionalnost", passportNumber: "Broj putovnice" }, contact: { title: "Kontaktni podaci", subtitle: "Potvrda rezervacije bit će poslana na ovaj kontakt.", firstName: "Ime", lastName: "Prezime", email: "E-mail adresa", phone: "Broj telefona" }, summary: { title: "Pregled rezervacije", flight: "Let", cabin: "Klasa", seat: "Sjedalo", passenger: "Putnik", contact: "Kontakt", total: "Ukupno", confirmAndPay: "Potvrdi i plati" }, payment: { title: "Plaćanje", cardNumber: "Broj kartice", expiry: "Rok važenja", cvv: "CVV", name: "Ime vlasnika kartice", payNow: "Plati sada", processing: "Obrađivanje..." }, confirmation: { title: "Rezervacija potvrđena!", subtitle: "Vaš let je spreman. Spakujte kofere!", reference: "Referentni broj", downloadTicket: "⬇ Preuzmi e-kartu", backHome: "Povratak na početnu" } },
  common: { back: "← Natrag", next: "Dalje →", loading: "Učitavanje...", error: "Došlo je do pogreške", close: "Zatvori" },
  locale: { language: "Jezik", currency: "Valuta", currentLanguage: "Trenutni jezik", allLanguages: "Svi jezici", popularCurrencies: "Popularne valute", allCurrencies: "Sve valute" },
};

// Catalan
export const ca = {
  nav: { book: "Reservar", flights: "Vols", myBooking: "La meva reserva" },
  home: { hero: "El teu viatge comença aquí", popularDestinations: "Destinacions populars" },
  search: { from: "Des de", to: "Fins a", date: "Data", passengers: "Passatgers", searchFlights: "Cercar vols", searching: "Cercant...", adult: "Adult", adults: "Adults", cabinClass: { economy: "Turista", premium_economy: "Turista Premium", business: "Business", first: "Primera classe" } },
  flights: { title: "Vols disponibles", noResults: "No s'han trobat vols", filters: "Filtres", cabinClass: "Classe de cabina", allClasses: "Totes les classes", nonStop: "Vol directe", select: "Seleccionar", status: { scheduled: "Programat", boarding: "Embarcament", departed: "Ha sortit", arrived: "Ha arribat", cancelled: "Cancel·lat" } },
  booking: { cabin: { title: "Seleccionar classe", selectFrom: "Seleccionar de", soldOut: "Esgotat" }, seat: { title: "Seleccionar seient", selected: "Seient seleccionat", available: "Disponible", occupied: "Ocupat", yourSeat: "El teu seient" }, passenger: { title: "Informació del passatger", passengerN: "Passatger", title_field: "Títol", firstName: "Nom", lastName: "Cognom", dateOfBirth: "Data de naixement", nationality: "Nacionalitat", passportNumber: "Número de passaport" }, contact: { title: "Informació de contacte", subtitle: "La confirmació s'enviarà a aquest contacte.", firstName: "Nom", lastName: "Cognom", email: "Adreça de correu electrònic", phone: "Número de telèfon" }, summary: { title: "Resum de la reserva", flight: "Vol", cabin: "Classe", seat: "Seient", passenger: "Passatger", contact: "Contacte", total: "Total", confirmAndPay: "Confirmar i pagar" }, payment: { title: "Pagament", cardNumber: "Número de targeta", expiry: "Venciment", cvv: "CVV", name: "Titular de la targeta", payNow: "Pagar ara", processing: "Processant..." }, confirmation: { title: "Reserva confirmada!", subtitle: "El teu vol està llest. Fes les maletes!", reference: "Referència de reserva", downloadTicket: "⬇ Descarregar e-ticket", backHome: "Tornar a l'inici" } },
  common: { back: "← Enrere", next: "Següent →", loading: "Carregant...", error: "S'ha produït un error", close: "Tancar" },
  locale: { language: "Idioma", currency: "Moneda", currentLanguage: "Idioma actual", allLanguages: "Tots els idiomes", popularCurrencies: "Monedes populars", allCurrencies: "Totes les monedes" },
};

// Persian/Farsi
export const fa = {
  nav: { book: "رزرو", flights: "پروازها", myBooking: "رزرو من" },
  home: { hero: "سفر شما از اینجا شروع می‌شود", popularDestinations: "مقاصد محبوب" },
  search: { from: "از", to: "به", date: "تاریخ", passengers: "مسافران", searchFlights: "جستجوی پرواز", searching: "در حال جستجو...", adult: "بزرگسال", adults: "بزرگسالان", cabinClass: { economy: "اقتصادی", premium_economy: "اقتصادی ممتاز", business: "تجاری", first: "اول" } },
  flights: { title: "پروازهای موجود", noResults: "پروازی یافت نشد", filters: "فیلترها", cabinClass: "کلاس کابین", allClasses: "همه کلاس‌ها", nonStop: "مستقیم", select: "انتخاب", status: { scheduled: "برنامه‌ریزی شده", boarding: "سوار شدن", departed: "پرواز کرد", arrived: "رسید", cancelled: "لغو شد" } },
  booking: { cabin: { title: "انتخاب کلاس", selectFrom: "انتخاب از", soldOut: "تمام شد" }, seat: { title: "انتخاب صندلی", selected: "صندلی انتخاب شده", available: "موجود", occupied: "اشغال", yourSeat: "صندلی شما" }, passenger: { title: "اطلاعات مسافر", passengerN: "مسافر", title_field: "عنوان", firstName: "نام", lastName: "نام خانوادگی", dateOfBirth: "تاریخ تولد", nationality: "ملیت", passportNumber: "شماره پاسپورت" }, contact: { title: "اطلاعات تماس", subtitle: "تأیید رزرو به این تماس ارسال می‌شود.", firstName: "نام", lastName: "نام خانوادگی", email: "آدرس ایمیل", phone: "شماره تلفن" }, summary: { title: "خلاصه رزرو", flight: "پرواز", cabin: "کلاس", seat: "صندلی", passenger: "مسافر", contact: "تماس", total: "جمع", confirmAndPay: "تأیید و پرداخت" }, payment: { title: "پرداخت", cardNumber: "شماره کارت", expiry: "انقضا", cvv: "CVV", name: "نام دارنده کارت", payNow: "پرداخت کنید", processing: "در حال پردازش..." }, confirmation: { title: "رزرو تأیید شد!", subtitle: "پرواز شما آماده است. چمدان‌هایتان را جمع کنید!", reference: "شماره مرجع رزرو", downloadTicket: "⬇ دانلود بلیط الکترونیکی", backHome: "بازگشت به خانه" } },
  common: { back: "← برگشت", next: "بعدی →", loading: "در حال بارگذاری...", error: "خطایی رخ داد", close: "بستن" },
  locale: { language: "زبان", currency: "ارز", currentLanguage: "زبان فعلی", allLanguages: "همه زبان‌ها", popularCurrencies: "ارزهای محبوب", allCurrencies: "همه ارزها" },
};

// Hebrew
export const he = {
  nav: { book: "הזמן", flights: "טיסות", myBooking: "ההזמנה שלי" },
  home: { hero: "המסע שלך מתחיל כאן", popularDestinations: "יעדים פופולריים" },
  search: { from: "מ", to: "אל", date: "תאריך", passengers: "נוסעים", searchFlights: "חפש טיסות", searching: "מחפש...", adult: "מבוגר", adults: "מבוגרים", cabinClass: { economy: "תיירות", premium_economy: "תיירות פרמיום", business: "עסקי", first: "ראשון" } },
  flights: { title: "טיסות זמינות", noResults: "לא נמצאו טיסות", filters: "מסננים", cabinClass: "מחלקה", allClasses: "כל המחלקות", nonStop: "ישיר", select: "בחר", status: { scheduled: "מתוכנן", boarding: "עלייה למטוס", departed: "המריא", arrived: "הגיע", cancelled: "בוטל" } },
  booking: { cabin: { title: "בחר מחלקה", selectFrom: "בחר מ", soldOut: "אזל" }, seat: { title: "בחר מושב", selected: "מושב נבחר", available: "זמין", occupied: "תפוס", yourSeat: "המושב שלך" }, passenger: { title: "פרטי נוסע", passengerN: "נוסע", title_field: "תואר", firstName: "שם פרטי", lastName: "שם משפחה", dateOfBirth: "תאריך לידה", nationality: "אזרחות", passportNumber: "מספר דרכון" }, contact: { title: "פרטי קשר", subtitle: "אישור ההזמנה ישלח לאיש קשר זה.", firstName: "שם פרטי", lastName: "שם משפחה", email: "כתובת דוא\"ל", phone: "מספר טלפון" }, summary: { title: "סיכום הזמנה", flight: "טיסה", cabin: "מחלקה", seat: "מושב", passenger: "נוסע", contact: "איש קשר", total: "סה\"כ", confirmAndPay: "אשר ושלם" }, payment: { title: "תשלום", cardNumber: "מספר כרטיס", expiry: "תפוגה", cvv: "CVV", name: "שם בעל הכרטיס", payNow: "שלם עכשיו", processing: "מעבד..." }, confirmation: { title: "ההזמנה אושרה!", subtitle: "הטיסה שלך מוכנה. ארוז את המזוודות!", reference: "מספר הפניה", downloadTicket: "⬇ הורד כרטיס אלקטרוני", backHome: "חזרה לדף הבית" } },
  common: { back: "← חזרה", next: "הבא →", loading: "טוען...", error: "אירעה שגיאה", close: "סגור" },
  locale: { language: "שפה", currency: "מטבע", currentLanguage: "שפה נוכחית", allLanguages: "כל השפות", popularCurrencies: "מטבעות פופולריים", allCurrencies: "כל המטבעות" },
};

// Bengali
export const bn = {
  nav: { book: "বুক করুন", flights: "ফ্লাইট", myBooking: "আমার বুকিং" },
  home: { hero: "আপনার যাত্রা এখান থেকে শুরু হয়", popularDestinations: "জনপ্রিয় গন্তব্য" },
  search: { from: "থেকে", to: "পর্যন্ত", date: "তারিখ", passengers: "যাত্রী", searchFlights: "ফ্লাইট খুঁজুন", searching: "খোঁজা হচ্ছে...", adult: "প্রাপ্তবয়স্ক", adults: "প্রাপ্তবয়স্ক", cabinClass: { economy: "ইকোনমি", premium_economy: "প্রিমিয়াম ইকোনমি", business: "বিজনেস", first: "ফার্স্ট" } },
  flights: { title: "উপলব্ধ ফ্লাইট", noResults: "কোনো ফ্লাইট পাওয়া যায়নি", filters: "ফিল্টার", cabinClass: "কেবিন ক্লাস", allClasses: "সব ক্লাস", nonStop: "নন-স্টপ", select: "নির্বাচন করুন", status: { scheduled: "নির্ধারিত", boarding: "বোর্ডিং", departed: "রওনা দিয়েছে", arrived: "পৌঁছেছে", cancelled: "বাতিল" } },
  booking: { cabin: { title: "কেবিন ক্লাস নির্বাচন করুন", selectFrom: "থেকে নির্বাচন করুন", soldOut: "বিক্রি হয়ে গেছে" }, seat: { title: "আসন নির্বাচন করুন", selected: "নির্বাচিত আসন", available: "উপলব্ধ", occupied: "দখল করা", yourSeat: "আপনার আসন" }, passenger: { title: "যাত্রীর তথ্য", passengerN: "যাত্রী", title_field: "পদবী", firstName: "নাম", lastName: "পদবী", dateOfBirth: "জন্ম তারিখ", nationality: "জাতীয়তা", passportNumber: "পাসপোর্ট নম্বর" }, contact: { title: "যোগাযোগের তথ্য", subtitle: "বুকিং নিশ্চিতকরণ এই যোগাযোগে পাঠানো হবে।", firstName: "নাম", lastName: "পদবী", email: "ইমেইল ঠিকানা", phone: "ফোন নম্বর" }, summary: { title: "বুকিং সারসংক্ষেপ", flight: "ফ্লাইট", cabin: "কেবিন", seat: "আসন", passenger: "যাত্রী", contact: "যোগাযোগ", total: "মোট", confirmAndPay: "নিশ্চিত করুন এবং পরিশোধ করুন" }, payment: { title: "পরিশোধ", cardNumber: "কার্ড নম্বর", expiry: "মেয়াদ উত্তীর্ণ", cvv: "CVV", name: "কার্ডধারকের নাম", payNow: "এখনই পরিশোধ করুন", processing: "প্রক্রিয়াকরণ..." }, confirmation: { title: "বুকিং নিশ্চিত হয়েছে!", subtitle: "আপনার ফ্লাইট প্রস্তুত। ব্যাগ গোছান!", reference: "বুকিং রেফারেন্স", downloadTicket: "⬇ ই-টিকিট ডাউনলোড করুন", backHome: "হোমে ফিরে যান" } },
  common: { back: "← পিছনে", next: "পরবর্তী →", loading: "লোড হচ্ছে...", error: "একটি ত্রুটি হয়েছে", close: "বন্ধ করুন" },
  locale: { language: "ভাষা", currency: "মুদ্রা", currentLanguage: "বর্তমান ভাষা", allLanguages: "সব ভাষা", popularCurrencies: "জনপ্রিয় মুদ্রা", allCurrencies: "সব মুদ্রা" },
};

// Urdu
export const ur = {
  nav: { book: "بک کریں", flights: "پروازیں", myBooking: "میری بکنگ" },
  home: { hero: "آپ کا سفر یہاں سے شروع ہوتا ہے", popularDestinations: "مقبول مقامات" },
  search: { from: "سے", to: "تک", date: "تاریخ", passengers: "مسافر", searchFlights: "پروازیں تلاش کریں", searching: "تلاش ہو رہی ہے...", adult: "بالغ", adults: "بالغ", cabinClass: { economy: "اکانومی", premium_economy: "پریمیم اکانومی", business: "بزنس", first: "فرسٹ" } },
  flights: { title: "دستیاب پروازیں", noResults: "کوئی پرواز نہیں ملی", filters: "فلٹر", cabinClass: "کیبن کلاس", allClasses: "تمام کلاسز", nonStop: "براہ راست", select: "منتخب کریں", status: { scheduled: "مقررہ", boarding: "سوار ہونا", departed: "روانہ ہوا", arrived: "پہنچا", cancelled: "منسوخ" } },
  booking: { cabin: { title: "کیبن کلاس منتخب کریں", selectFrom: "سے منتخب کریں", soldOut: "فروخت ہو گیا" }, seat: { title: "سیٹ منتخب کریں", selected: "منتخب سیٹ", available: "دستیاب", occupied: "مصروف", yourSeat: "آپ کی سیٹ" }, passenger: { title: "مسافر کی معلومات", passengerN: "مسافر", title_field: "لقب", firstName: "نام", lastName: "خاندانی نام", dateOfBirth: "تاریخ پیدائش", nationality: "قومیت", passportNumber: "پاسپورٹ نمبر" }, contact: { title: "رابطہ معلومات", subtitle: "بکنگ کی تصدیق اس رابطے پر بھیجی جائے گی۔", firstName: "نام", lastName: "خاندانی نام", email: "ای میل پتہ", phone: "فون نمبر" }, summary: { title: "بکنگ کا خلاصہ", flight: "پرواز", cabin: "کیبن", seat: "سیٹ", passenger: "مسافر", contact: "رابطہ", total: "کل", confirmAndPay: "تصدیق کریں اور ادا کریں" }, payment: { title: "ادائیگی", cardNumber: "کارڈ نمبر", expiry: "میعاد", cvv: "CVV", name: "کارڈ ہولڈر کا نام", payNow: "ابھی ادا کریں", processing: "پروسیسنگ..." }, confirmation: { title: "بکنگ کی تصدیق ہو گئی!", subtitle: "آپ کی پرواز تیار ہے۔ سامان باندھیں!", reference: "بکنگ حوالہ", downloadTicket: "⬇ ای-ٹکٹ ڈاؤن لوڈ کریں", backHome: "ہوم پر واپس جائیں" } },
  common: { back: "← واپس", next: "اگلا →", loading: "لوڈ ہو رہا ہے...", error: "ایک خرابی ہوئی", close: "بند کریں" },
  locale: { language: "زبان", currency: "کرنسی", currentLanguage: "موجودہ زبان", allLanguages: "تمام زبانیں", popularCurrencies: "مقبول کرنسیاں", allCurrencies: "تمام کرنسیاں" },
};

// Lithuanian
export const lt = {
  nav: { book: "Rezervuoti", flights: "Skrydžiai", myBooking: "Mano rezervacija" },
  home: { hero: "Jūsų kelionė prasideda čia", popularDestinations: "Populiarios kryptys" },
  search: { from: "Iš", to: "Į", date: "Data", passengers: "Keleiviai", searchFlights: "Ieškoti skrydžių", searching: "Ieškoma...", adult: "Suaugęs", adults: "Suaugę", cabinClass: { economy: "Ekonominė", premium_economy: "Aukštesnė ekonominė", business: "Verslo", first: "Pirmoji klasė" } },
  flights: { title: "Galimi skrydžiai", noResults: "Skrydžių nerasta", filters: "Filtrai", cabinClass: "Kabinos klasė", allClasses: "Visos klasės", nonStop: "Tiesioginis", select: "Pasirinkti", status: { scheduled: "Suplanuotas", boarding: "Įlaipinimas", departed: "Išvyko", arrived: "Atvyko", cancelled: "Atšauktas" } },
  booking: { cabin: { title: "Pasirinkti klasę", selectFrom: "Pasirinkti iš", soldOut: "Išparduota" }, seat: { title: "Pasirinkti vietą", selected: "Pasirinkta vieta", available: "Prieinama", occupied: "Užimta", yourSeat: "Jūsų vieta" }, passenger: { title: "Keleivio informacija", passengerN: "Keleivis", title_field: "Kreipinys", firstName: "Vardas", lastName: "Pavardė", dateOfBirth: "Gimimo data", nationality: "Pilietybė", passportNumber: "Paso numeris" }, contact: { title: "Kontaktinė informacija", subtitle: "Rezervacijos patvirtinimas bus išsiųstas šiam kontaktui.", firstName: "Vardas", lastName: "Pavardė", email: "El. pašto adresas", phone: "Telefono numeris" }, summary: { title: "Rezervacijos santrauka", flight: "Skrydis", cabin: "Klasė", seat: "Vieta", passenger: "Keleivis", contact: "Kontaktas", total: "Iš viso", confirmAndPay: "Patvirtinti ir mokėti" }, payment: { title: "Mokėjimas", cardNumber: "Kortelės numeris", expiry: "Galiojimo laikas", cvv: "CVV", name: "Kortelės savininko vardas", payNow: "Mokėti dabar", processing: "Apdorojama..." }, confirmation: { title: "Rezervacija patvirtinta!", subtitle: "Jūsų skrydis paruoštas. Susikraukite lagaminus!", reference: "Rezervacijos nuoroda", downloadTicket: "⬇ Atsisiųsti e-bilietą", backHome: "Grįžti į pradžią" } },
  common: { back: "← Atgal", next: "Kitas →", loading: "Įkeliama...", error: "Įvyko klaida", close: "Uždaryti" },
  locale: { language: "Kalba", currency: "Valiuta", currentLanguage: "Dabartinė kalba", allLanguages: "Visos kalbos", popularCurrencies: "Populiarios valiutos", allCurrencies: "Visos valiutos" },
};

// Latvian
export const lv = {
  nav: { book: "Rezervēt", flights: "Lidojumi", myBooking: "Mana rezervācija" },
  home: { hero: "Jūsu ceļojums sākas šeit", popularDestinations: "Populārie galamērķi" },
  search: { from: "No", to: "Uz", date: "Datums", passengers: "Pasažieri", searchFlights: "Meklēt lidojumus", searching: "Meklē...", adult: "Pieaugušais", adults: "Pieaugušie", cabinClass: { economy: "Ekonomiskā", premium_economy: "Premium ekonomiskā", business: "Biznesa", first: "Pirmā klase" } },
  flights: { title: "Pieejamie lidojumi", noResults: "Lidojumi nav atrasti", filters: "Filtri", cabinClass: "Kabīnes klase", allClasses: "Visas klases", nonStop: "Tiešais", select: "Izvēlēties", status: { scheduled: "Plānots", boarding: "Iekāpšana", departed: "Izlidojis", arrived: "Ielidojis", cancelled: "Atcelts" } },
  booking: { cabin: { title: "Izvēlēties klasi", selectFrom: "Izvēlēties no", soldOut: "Izpārdots" }, seat: { title: "Izvēlēties sēdekli", selected: "Izvēlētais sēdeklis", available: "Pieejams", occupied: "Aizņemts", yourSeat: "Jūsu sēdeklis" }, passenger: { title: "Pasažiera informācija", passengerN: "Pasažieris", title_field: "Uzruna", firstName: "Vārds", lastName: "Uzvārds", dateOfBirth: "Dzimšanas datums", nationality: "Pilsonība", passportNumber: "Pases numurs" }, contact: { title: "Kontaktinformācija", subtitle: "Rezervācijas apstiprinājums tiks nosūtīts šim kontaktam.", firstName: "Vārds", lastName: "Uzvārds", email: "E-pasta adrese", phone: "Tālruņa numurs" }, summary: { title: "Rezervācijas kopsavilkums", flight: "Lidojums", cabin: "Klase", seat: "Sēdeklis", passenger: "Pasažieris", contact: "Kontakts", total: "Kopā", confirmAndPay: "Apstiprināt un maksāt" }, payment: { title: "Maksājums", cardNumber: "Kartes numurs", expiry: "Derīguma termiņš", cvv: "CVV", name: "Kartes īpašnieka vārds", payNow: "Maksāt tagad", processing: "Apstrādā..." }, confirmation: { title: "Rezervācija apstiprināta!", subtitle: "Jūsu lidojums ir gatavs. Sakravājiet čemodānus!", reference: "Rezervācijas numurs", downloadTicket: "⬇ Lejupielādēt e-biļeti", backHome: "Atpakaļ uz sākumu" } },
  common: { back: "← Atpakaļ", next: "Tālāk →", loading: "Ielādē...", error: "Radās kļūda", close: "Aizvērt" },
  locale: { language: "Valoda", currency: "Valūta", currentLanguage: "Pašreizējā valoda", allLanguages: "Visas valodas", popularCurrencies: "Populārās valūtas", allCurrencies: "Visas valūtas" },
};
