// Remaining language translations

// Estonian
export const et = {
  nav: { book: "Broneeri", flights: "Lennud", myBooking: "Minu broneering" },
  home: { hero: "Sinu teekond algab siit", popularDestinations: "Populaarsed sihtkohad" },
  search: { from: "Kust", to: "Kuhu", date: "Kuupäev", passengers: "Reisijad", searchFlights: "Otsi lende", searching: "Otsin...", adult: "Täiskasvanu", adults: "Täiskasvanud", cabinClass: { economy: "Economy", premium_economy: "Premium Economy", business: "Äri", first: "Esimene klass" } },
  flights: { title: "Saadaolevad lennud", noResults: "Lende ei leitud", filters: "Filtrid", cabinClass: "Kabiiniklass", allClasses: "Kõik klassid", nonStop: "Otselend", select: "Vali", status: { scheduled: "Planeeritud", boarding: "Pardaleminek", departed: "Väljunud", arrived: "Saabunud", cancelled: "Tühistatud" } },
  booking: { cabin: { title: "Vali klass", selectFrom: "Vali", soldOut: "Välja müüdud" }, seat: { title: "Vali istekoht", selected: "Valitud istekoht", available: "Saadaval", occupied: "Hõivatud", yourSeat: "Sinu istekoht" }, passenger: { title: "Reisija andmed", passengerN: "Reisija", title_field: "Tiitel", firstName: "Eesnimi", lastName: "Perekonnanimi", dateOfBirth: "Sünnikuupäev", nationality: "Rahvus", passportNumber: "Passi number" }, contact: { title: "Kontaktandmed", subtitle: "Broneeringu kinnitus saadetakse sellele kontaktile.", firstName: "Eesnimi", lastName: "Perekonnanimi", email: "E-posti aadress", phone: "Telefoninumber" }, summary: { title: "Broneeringu kokkuvõte", flight: "Lend", cabin: "Klass", seat: "Istekoht", passenger: "Reisija", contact: "Kontakt", total: "Kokku", confirmAndPay: "Kinnita ja maksa" }, payment: { title: "Makse", cardNumber: "Kaardi number", expiry: "Aegumiskuupäev", cvv: "CVV", name: "Kaardi omaniku nimi", payNow: "Maksa kohe", processing: "Töötlen..." }, confirmation: { title: "Broneering kinnitatud!", subtitle: "Sinu lend on valmis. Paki kohvrid!", reference: "Broneeringu number", downloadTicket: "⬇ Laadi alla e-pilet", backHome: "Tagasi avalehele" } },
  common: { back: "← Tagasi", next: "Edasi →", loading: "Laadin...", error: "Tekkis viga", close: "Sulge" },
  locale: { language: "Keel", currency: "Valuuta", currentLanguage: "Praegune keel", allLanguages: "Kõik keeled", popularCurrencies: "Populaarsed valuutad", allCurrencies: "Kõik valuutad" },
};

// Serbian
export const sr = {
  nav: { book: "Резервишите", flights: "Летови", myBooking: "Моја резервација" },
  home: { hero: "Ваше путовање почиње овде", popularDestinations: "Популарне дестинације" },
  search: { from: "Из", to: "У", date: "Датум", passengers: "Путници", searchFlights: "Тражи летове", searching: "Тражење...", adult: "Одрасли", adults: "Одрасли", cabinClass: { economy: "Економска", premium_economy: "Премиум економска", business: "Пословна", first: "Прва класа" } },
  flights: { title: "Доступни летови", noResults: "Нису пронађени летови", filters: "Филтри", cabinClass: "Класа кабине", allClasses: "Све класе", nonStop: "Директан лет", select: "Одабери", status: { scheduled: "Заказано", boarding: "Укрцавање", departed: "Одлетео", arrived: "Стигао", cancelled: "Отказано" } },
  booking: { cabin: { title: "Одабери класу", selectFrom: "Одабери из", soldOut: "Распродато" }, seat: { title: "Одабери седиште", selected: "Одабрано седиште", available: "Доступно", occupied: "Заузето", yourSeat: "Ваше седиште" }, passenger: { title: "Подаци путника", passengerN: "Путник", title_field: "Titula", firstName: "Ime", lastName: "Prezime", dateOfBirth: "Datum rođenja", nationality: "Nacionalnost", passportNumber: "Broj pasoša" }, contact: { title: "Kontakt podaci", subtitle: "Potvrda rezervacije biće poslata na ovaj kontakt.", firstName: "Ime", lastName: "Prezime", email: "E-mail adresa", phone: "Broj telefona" }, summary: { title: "Pregled rezervacije", flight: "Let", cabin: "Klasa", seat: "Sedište", passenger: "Putnik", contact: "Kontakt", total: "Ukupno", confirmAndPay: "Potvrdi i plati" }, payment: { title: "Plaćanje", cardNumber: "Broj kartice", expiry: "Rok važenja", cvv: "CVV", name: "Ime vlasnika kartice", payNow: "Plati sada", processing: "Obrada..." }, confirmation: { title: "Rezervacija potvrđena!", subtitle: "Vaš let je spreman. Spakovajte kofere!", reference: "Referentni broj", downloadTicket: "⬇ Preuzmi e-kartu", backHome: "Povratak na početnu" } },
  common: { back: "← Nazad", next: "Dalje →", loading: "Učitavanje...", error: "Došlo je do greške", close: "Zatvori" },
  locale: { language: "Jezik", currency: "Valuta", currentLanguage: "Trenutni jezik", allLanguages: "Svi jezici", popularCurrencies: "Popularne valute", allCurrencies: "Sve valute" },
};

// Swahili
export const sw = {
  nav: { book: "Hifadhi", flights: "Ndege", myBooking: "Uhifadhi wangu" },
  home: { hero: "Safari yako inaanza hapa", popularDestinations: "Maeneo maarufu" },
  search: { from: "Kutoka", to: "Kwenda", date: "Tarehe", passengers: "Abiria", searchFlights: "Tafuta ndege", searching: "Inatafuta...", adult: "Mtu mzima", adults: "Watu wazima", cabinClass: { economy: "Uchumi", premium_economy: "Uchumi wa Juu", business: "Biashara", first: "Darasa la Kwanza" } },
  flights: { title: "Ndege zilizopo", noResults: "Hakuna ndege zilizopatikana", filters: "Vichujio", cabinClass: "Darasa la kabini", allClasses: "Madarasa yote", nonStop: "Moja kwa moja", select: "Chagua", status: { scheduled: "Ilipangwa", boarding: "Kupanda", departed: "Imeondoka", arrived: "Imefika", cancelled: "Imefutwa" } },
  booking: { cabin: { title: "Chagua darasa", selectFrom: "Chagua kutoka", soldOut: "Imeisha" }, seat: { title: "Chagua kiti", selected: "Kiti kilichochaguliwa", available: "Inapatikana", occupied: "Imechukuliwa", yourSeat: "Kiti chako" }, passenger: { title: "Taarifa za abiria", passengerN: "Abiria", title_field: "Cheo", firstName: "Jina la kwanza", lastName: "Jina la familia", dateOfBirth: "Tarehe ya kuzaliwa", nationality: "Utaifa", passportNumber: "Nambari ya pasipoti" }, contact: { title: "Taarifa za mawasiliano", subtitle: "Uthibitisho wa uhifadhi utumwe kwa mawasiliano haya.", firstName: "Jina la kwanza", lastName: "Jina la familia", email: "Anwani ya barua pepe", phone: "Nambari ya simu" }, summary: { title: "Muhtasari wa uhifadhi", flight: "Ndege", cabin: "Darasa", seat: "Kiti", passenger: "Abiria", contact: "Mawasiliano", total: "Jumla", confirmAndPay: "Thibitisha na Lipa" }, payment: { title: "Malipo", cardNumber: "Nambari ya kadi", expiry: "Tarehe ya kumalizika", cvv: "CVV", name: "Jina la mmiliki wa kadi", payNow: "Lipa sasa", processing: "Inashughulikiwa..." }, confirmation: { title: "Uhifadhi umethibitishwa!", subtitle: "Ndege yako iko tayari. Funga mabegi!", reference: "Nambari ya kumbukumbu", downloadTicket: "⬇ Pakua tiketi ya elektroniki", backHome: "Rudi nyumbani" } },
  common: { back: "← Rudi", next: "Inayofuata →", loading: "Inapakia...", error: "Hitilafu imetokea", close: "Funga" },
  locale: { language: "Lugha", currency: "Sarafu", currentLanguage: "Lugha ya sasa", allLanguages: "Lugha zote", popularCurrencies: "Sarafu maarufu", allCurrencies: "Sarafu zote" },
};

// Filipino/Tagalog
export const tl = {
  nav: { book: "Mag-book", flights: "Mga Lipad", myBooking: "Aking Booking" },
  home: { hero: "Ang iyong paglalakbay ay nagsisimula dito", popularDestinations: "Mga sikat na destinasyon" },
  search: { from: "Mula", to: "Patungo", date: "Petsa", passengers: "Mga Pasahero", searchFlights: "Maghanap ng mga lipad", searching: "Naghahanap...", adult: "Matanda", adults: "Mga Matanda", cabinClass: { economy: "Economy", premium_economy: "Premium Economy", business: "Business", first: "First Class" } },
  flights: { title: "Mga available na lipad", noResults: "Walang nahanap na lipad", filters: "Mga Filter", cabinClass: "Klase ng Cabin", allClasses: "Lahat ng Klase", nonStop: "Direkta", select: "Pumili", status: { scheduled: "Nakaplanong", boarding: "Boarding", departed: "Umalis na", arrived: "Dumating na", cancelled: "Kinansela" } },
  booking: { cabin: { title: "Pumili ng klase", selectFrom: "Pumili mula sa", soldOut: "Sold Out" }, seat: { title: "Pumili ng upuan", selected: "Napiling upuan", available: "Available", occupied: "Inookupahan", yourSeat: "Iyong upuan" }, passenger: { title: "Impormasyon ng pasahero", passengerN: "Pasahero", title_field: "Titulo", firstName: "Unang pangalan", lastName: "Apelyido", dateOfBirth: "Petsa ng kapanganakan", nationality: "Nasyonalidad", passportNumber: "Numero ng Pasaporte" }, contact: { title: "Impormasyon ng Pakikipag-ugnayan", subtitle: "Ang kumpirmasyon ng booking ay ipapadala sa contact na ito.", firstName: "Unang pangalan", lastName: "Apelyido", email: "Email address", phone: "Numero ng telepono" }, summary: { title: "Buod ng Booking", flight: "Lipad", cabin: "Klase", seat: "Upuan", passenger: "Pasahero", contact: "Contact", total: "Kabuuan", confirmAndPay: "Kumpirmahin at Bayaran" }, payment: { title: "Bayad", cardNumber: "Numero ng Card", expiry: "Petsa ng Pag-expire", cvv: "CVV", name: "Pangalan ng May-ari ng Card", payNow: "Bayaran Ngayon", processing: "Pinoproseso..." }, confirmation: { title: "Nakumpirma ang Booking!", subtitle: "Handa na ang iyong lipad. Maghanda ng mga bag!", reference: "Sanggunian ng Booking", downloadTicket: "⬇ I-download ang E-Ticket", backHome: "Bumalik sa Home" } },
  common: { back: "← Bumalik", next: "Susunod →", loading: "Naglo-load...", error: "May naganap na error", close: "Isara" },
  locale: { language: "Wika", currency: "Pera", currentLanguage: "Kasalukuyang Wika", allLanguages: "Lahat ng Wika", popularCurrencies: "Mga Sikat na Pera", allCurrencies: "Lahat ng Pera" },
};

// Georgian
export const ka = {
  nav: { book: "დაჯავშნა", flights: "რეისები", myBooking: "ჩემი დაჯავშნა" },
  home: { hero: "თქვენი მოგზაურობა აქ იწყება", popularDestinations: "პოპულარული დანიშნულება" },
  search: { from: "საიდან", to: "სად", date: "თარიღი", passengers: "მგზავრები", searchFlights: "რეისების ძიება", searching: "ძიება...", adult: "მოზრდილი", adults: "მოზრდილები", cabinClass: { economy: "ეკონომი", premium_economy: "პრემიუმ ეკონომი", business: "ბიზნესი", first: "პირველი კლასი" } },
  flights: { title: "ხელმისაწვდომი რეისები", noResults: "რეისები ვერ მოიძებნა", filters: "ფილტრები", cabinClass: "კაბინის კლასი", allClasses: "ყველა კლასი", nonStop: "პირდაპირი", select: "არჩევა", status: { scheduled: "დაგეგმილი", boarding: "ჩასხდომა", departed: "გაფრინდა", arrived: "ჩამოვიდა", cancelled: "გაუქმებული" } },
  booking: { cabin: { title: "კლასის არჩევა", selectFrom: "არჩევა", soldOut: "გაყიდულია" }, seat: { title: "ადგილის არჩევა", selected: "არჩეული ადგილი", available: "ხელმისაწვდომი", occupied: "დაკავებული", yourSeat: "თქვენი ადგილი" }, passenger: { title: "მგზავრის ინფორმაცია", passengerN: "მგზავრი", title_field: "წოდება", firstName: "სახელი", lastName: "გვარი", dateOfBirth: "დაბადების თარიღი", nationality: "ეროვნება", passportNumber: "პასპორტის ნომერი" }, contact: { title: "საკონტაქტო ინფორმაცია", subtitle: "დაჯავშნის დადასტურება გაეგზავნება ამ კონტაქტს.", firstName: "სახელი", lastName: "გვარი", email: "ელფოსტის მისამართი", phone: "ტელეფონის ნომერი" }, summary: { title: "დაჯავშნის შეჯამება", flight: "რეისი", cabin: "კლასი", seat: "ადგილი", passenger: "მგზავრი", contact: "კონტაქტი", total: "სულ", confirmAndPay: "დადასტურება და გადახდა" }, payment: { title: "გადახდა", cardNumber: "ბარათის ნომერი", expiry: "ვადა", cvv: "CVV", name: "ბარათის მფლობელის სახელი", payNow: "გადაიხადეთ ახლა", processing: "მუშავდება..." }, confirmation: { title: "დაჯავშნა დადასტურდა!", subtitle: "თქვენი რეისი მზადაა. შეფუთეთ ჩანთები!", reference: "დაჯავშნის ნომერი", downloadTicket: "⬇ ელ-ბილეთის ჩამოტვირთვა", backHome: "მთავარ გვერდზე დაბრუნება" } },
  common: { back: "← უკან", next: "შემდეგი →", loading: "იტვირთება...", error: "მოხდა შეცდომა", close: "დახურვა" },
  locale: { language: "ენა", currency: "ვალუტა", currentLanguage: "მიმდინარე ენა", allLanguages: "ყველა ენა", popularCurrencies: "პოპულარული ვალუტები", allCurrencies: "ყველა ვალუტა" },
};
